services:
  db:
    image: mysql:8.0
    container_name: rest-spring-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbmysql
      MYSQL_USER: wagner
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
